/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libluv_my_mylibluv01_MainActivity */

#ifndef _Included_com_libluv_my_mylibluv01_MainActivity
#define _Included_com_libluv_my_mylibluv01_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libluv_my_mylibluv01_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libluv_my_mylibluv01_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
