/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libluv_my_mylibluv01_Test */

#ifndef _Included_com_libluv_my_mylibluv01_Test
#define _Included_com_libluv_my_mylibluv01_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libluv_my_mylibluv01_Test
 * Method:    argbtoi420
 * Signature: ([BI[BI[BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_libluv_my_mylibluv01_Test_argbtoi420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_libluv_my_mylibluv01_Test
 * Method:    convertToI420
 * Signature: ([BI[BI[BI[BIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_libluv_my_mylibluv01_Test_convertToI420
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_libluv_my_mylibluv01_Test
 * Method:    convertToArgb
 * Signature: ([BI[BIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_libluv_my_mylibluv01_Test_convertToArgb
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
